# Generated by Django 5.1.1 on 2024-09-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
