# Generated by Django 5.1.1 on 2024-09-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_flag',
            field=models.BooleanField(default='False'),
        ),
    ]
