# Generated by Django 5.1.1 on 2024-09-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_active_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active_flag',
            field=models.BooleanField(default='True'),
        ),
    ]
