# Generated by Django 5.1.1 on 2024-09-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_active_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
    ]
