# Generated by Django 5.1.1 on 2024-09-30 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='own_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
