# Generated by Django 5.1.1 on 2024-10-05 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_bid_current_bid_alter_bid_start_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='start_bid',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
