# Generated by Django 5.1.1 on 2024-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
